import requests

def 获取商品数据(cookie_value1):
    headers = {
        'accept': '*/*',
        'accept-language': 'zh-CN,zh;q=0.9',
        'anti-content': requests.get('http://106.75.215.11:9000/api/0as').json().get('data'),
        'cache-control': 'max-age=0',
        'content-type': 'application/json',
        'origin': 'https://mms.pinduoduo.com',
        'priority': 'u=1, i',
        'referer': 'https://mms.pinduoduo.com/goods/goods_detail?goods_id=925951937221&page_num=14',
        'sec-ch-ua': '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
        'cookie': cookie_value1,
    }

    good_id = 929421783014

    json_data = {
        'goods_id': good_id,
    }

    response = requests.post(
        'https://mms.pinduoduo.com/glide/v2/mms/query/commit/on_shop/detail',
        headers=headers,
        json=json_data,
    )



#成功响应
# {
#     "success": true,
#     "error_code": 1000000,
#     "error_msg": null,
#     "result": {
#         "goods_commit_id": 186960264919,
#         "goods_id": 925951937221,
#         "goods_sn": "2603245951937221",
#         "out_goods_sn": "",
#         "cost_template_id": 544142245494784,
#         "same_city_template_id": 0,
#         "cat_id": 26945,
#         "cats": [
#             "内衣裤袜",
#             "女士袜子/丝袜/打底裤袜",
#             "过膝袜",
#             null
#         ],
#         "tiny_name": "",
#         "warm_tips": "",
#         "is_folt": 0,
#         "fabric": "",
#         "fabric_content": "",
#         "fabric_id": null,
#         "fabric_content_id": null,
#         "mall_id": 974346487,
#         "mall_name": "正好Inright遇见",
#         "goods_name": "春夏薄款天鹅绒过膝袜JK风防滑显瘦甜美高筒袜少女学生款踏青春游",
#         "goods_desc": "春夏薄款天鹅绒过膝袜JK风防滑显瘦甜美高筒袜少女学生款踏青春游",
#         "share_desc": "春夏薄款天鹅绒过膝袜JK风防滑显瘦甜美高筒袜少女学生款踏青春游",
#         "list_desc": [],
#         "market_price": 2080,
#         "thumb_url": "https://img.pddpic.com/gaudit-image/2026-03-24/e959c0355f548bad72222cb1233206d6.jpeg",
#         "hd_thumb_url": "https://img.pddpic.com/gaudit-image/2026-03-24/9942adfb7eef751b803707b2d80c5eca.jpeg",
#         "image_url": "",
#         "allowed_region": [
#             2,
#             3,
#             4,
#             5,
#             6,
#             7,
#             8,
#             9,
#             10,
#             11,
#             12,
#             13,
#             14,
#             15,
#             16,
#             17,
#             18,
#             19,
#             20,
#             21,
#             22,
#             23,
#             24,
#             25,
#             26,
#             27,
#             28,
#             29,
#             30,
#             31,
#             32
#         ],
#         "region_limit": 0,
#         "goods_type": 1,
#         "goods_type_name": "普通商品",
#         "country_id": 0,
#         "country_name": null,
#         "warehouse": "",
#         "event_type": 0,
#         "is_app": 0,
#         "is_pre_sale": 0,
#         "pre_sale_time": 0,
#         "is_refundable": 1,
#         "is_customs": 0,
#         "customs": "",
#         "is_bangdan": 0,
#         "shipment_limit_second": 172800,
#         "quick_refund": 0,
#         "created_at": 1774341831,
#         "commit_extension": {
#             "id": 0,
#             "goods_commit_id": 0,
#             "start_production_date": 0,
#             "end_production_date": 0,
#             "production_license": "",
#             "production_standard_number": "",
#             "shelf_life": 0,
#             "out_goods_sn": "",
#             "created_at": null,
#             "updated_at": null
#         },
#         "groups": {
#             "single_price": 0,
#             "group_price": 0,
#             "carnival_price": null,
#             "customer_num": 2,
#             "buy_limit": 999999,
#             "order_limit": 999999,
#             "regular_limit": null,
#             "regular_limit_duration": null,
#             "min_num_of_order": null
#         },
#         "carousel_gallery": [
#             {
#                 "url": "https://img.pddpic.com/garner-api-new/cedc7453af2c3f3a358f1e59dee55d33.jpeg",
#                 "width": 1500,
#                 "height": 1500,
#                 "type": 1,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818610287,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/garner-api-new/e039072e9b80a9d2f3c0b3137b4404b1.jpeg",
#                 "width": 1500,
#                 "height": 1500,
#                 "type": 1,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818581852,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/garner-api-new/670e24f83a0f72f5ef97232f1d88b4e8.jpeg",
#                 "width": 1500,
#                 "height": 1500,
#                 "type": 1,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818602296,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/garner-api-new/0e486c39e24c23d5f1a2493cd98be441.jpeg",
#                 "width": 1500,
#                 "height": 1500,
#                 "type": 1,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818609277,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/garner-api-new/f8223778aab75604186d0d3d08cdecdf.jpeg",
#                 "width": 1500,
#                 "height": 1500,
#                 "type": 1,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818624116,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/garner-api-new/0a3abf845ac7fec915fc7177024304e5.jpeg",
#                 "width": 1500,
#                 "height": 1500,
#                 "type": 1,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818617522,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             }
#         ],
#         "detail_gallery": [
#             {
#                 "url": "https://img.pddpic.com/mms-goods-image/2026-03-24/70b58cd2-7df3-4106-8e7d-573d8a8a963a.jpeg",
#                 "width": 1200,
#                 "height": 1200,
#                 "type": 2,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818658185,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/mms-goods-image/2026-03-24/bcb38036-2e23-4372-92c8-7f91c81dc0b9.jpeg",
#                 "width": 1200,
#                 "height": 1200,
#                 "type": 2,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818652393,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/mms-goods-image/2026-03-24/e119ac8a-6673-4be5-a17c-60ba1386e2eb.jpeg",
#                 "width": 1200,
#                 "height": 1200,
#                 "type": 2,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818641739,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/mms-goods-image/2026-03-24/d4d9affa-341a-4e5c-904e-46d2920af2a9.jpeg",
#                 "width": 1200,
#                 "height": 1200,
#                 "type": 2,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818656234,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/mms-goods-image/2026-03-24/a674baa4-b633-419e-94bf-04f228ee62a5.jpeg",
#                 "width": 1200,
#                 "height": 1200,
#                 "type": 2,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818647660,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/mms-goods-image/2026-03-24/369b960f-7d20-4d8d-a92c-ea77eaeedb3e.jpeg",
#                 "width": 1200,
#                 "height": 1200,
#                 "type": 2,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818646613,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             },
#             {
#                 "url": "https://img.pddpic.com/mms-goods-image/2026-03-24/c23d3e7d-28c3-4025-bc56-75d18afa6c49.jpeg",
#                 "width": 1200,
#                 "height": 1200,
#                 "type": 2,
#                 "source": null,
#                 "status": null,
#                 "video_url": null,
#                 "file_id": 85818931896,
#                 "is_deleted": null,
#                 "check_comment": null,
#                 "origin_url": null
#             }
#         ],
#         "label_gallery": [],
#         "nutrition_gallery": [],
#         "ingredient_gallery": [],
#         "carousel_ai_gallery": [],
#         "video_gallery": [],
#         "recommend_aivideo": [],
#         "explanation_video_gallery": [],
#         "size_gallery": [],
#         "medical_device_certificate_gallery": [],
#         "skus": [
#             {
#                 "id": null,
#                 "sku_id": 1874880557321,
#                 "sku_sn": null,
#                 "carnival_price": 0,
#                 "init_quantity": 0,
#                 "is_onsale": 1,
#                 "limit_quantity": 999999,
#                 "multi_price": 980,
#                 "multi_price_in_yuan": null,
#                 "price": 1080,
#                 "price_in_yuan": null,
#                 "quantity": 1000,
#                 "reserve_quantity": 0,
#                 "weight": 0,
#                 "thumb_url": "https://img.pddpic.com/mms-goods-image/2026-03-24/369b960f-7d20-4d8d-a92c-ea77eaeedb3e.jpeg",
#                 "thumb_url_file_id": 85818646613,
#                 "thumb_url_status": null,
#                 "thumb_url_is_deleted": null,
#                 "quantity_delta": 1000,
#                 "spec": [
#                     {
#                         "parent_id": 1215,
#                         "parent_name": "颜色",
#                         "spec_id": 26866365144,
#                         "spec_name": "黑色【一】双",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     },
#                     {
#                         "parent_id": 1226,
#                         "parent_name": "尺码",
#                         "spec_id": 55256868,
#                         "spec_name": "【150-175】",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     }
#                 ],
#                 "out_sku_sn": "2049-GXH1",
#                 "batch_id": null,
#                 "priority": 0,
#                 "ware_id": null,
#                 "ware_biz_type": null,
#                 "advice_price": null,
#                 "length": null,
#                 "oversea_sku": {
#                     "specifications": null,
#                     "measurement_code": null,
#                     "measurement_unit": null,
#                     "taxation": null,
#                     "record_id_list": null
#                 },
#                 "cspu_id": null,
#                 "child_skus": null,
#                 "ref_sku_commit_id": 3137984564886,
#                 "start_time": null,
#                 "end_time": null,
#                 "sku_srv_templates": null,
#                 "calendar_rule_id": null,
#                 "hot_live_group": null,
#                 "pre_sale_time": 0,
#                 "out_source_sku_id": null,
#                 "dd_grocery_sku_params": null,
#                 "sku_extended_attribute_dtos": null,
#                 "sku_basic_property_dtos": null,
#                 "spec_note_map": null,
#                 "delivery_schedule_dtos": null,
#                 "shipment_limit_second_list": [],
#                 "sku69_code": "",
#                 "outer_product_url": null,
#                 "internal_product_url": null,
#                 "vas_platform_install_convert_id": null,
#                 "vas_platform_dismantle_and_home_install_convert_id": null,
#                 "vas_platform_dismantle_taken_and_home_install_convert_id": null
#             },
#             {
#                 "id": null,
#                 "sku_id": 1874880557322,
#                 "sku_sn": null,
#                 "carnival_price": 0,
#                 "init_quantity": 0,
#                 "is_onsale": 1,
#                 "limit_quantity": 999999,
#                 "multi_price": 1480,
#                 "multi_price_in_yuan": null,
#                 "price": 1580,
#                 "price_in_yuan": null,
#                 "quantity": 1000,
#                 "reserve_quantity": 0,
#                 "weight": 0,
#                 "thumb_url": "https://img.pddpic.com/mms-goods-image/2026-03-24/25c25077-f31e-4bbf-bfe7-edb17802b5ec.jpeg.a.jpeg",
#                 "thumb_url_file_id": 85818924856,
#                 "thumb_url_status": null,
#                 "thumb_url_is_deleted": null,
#                 "quantity_delta": 1000,
#                 "spec": [
#                     {
#                         "parent_id": 1215,
#                         "parent_name": "颜色",
#                         "spec_id": 29024355058,
#                         "spec_name": "黑色【两】双",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     },
#                     {
#                         "parent_id": 1226,
#                         "parent_name": "尺码",
#                         "spec_id": 55256868,
#                         "spec_name": "【150-175】",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     }
#                 ],
#                 "out_sku_sn": "2049-GXH2",
#                 "batch_id": null,
#                 "priority": 1,
#                 "ware_id": null,
#                 "ware_biz_type": null,
#                 "advice_price": null,
#                 "length": null,
#                 "oversea_sku": {
#                     "specifications": null,
#                     "measurement_code": null,
#                     "measurement_unit": null,
#                     "taxation": null,
#                     "record_id_list": null
#                 },
#                 "cspu_id": null,
#                 "child_skus": null,
#                 "ref_sku_commit_id": 3137984564887,
#                 "start_time": null,
#                 "end_time": null,
#                 "sku_srv_templates": null,
#                 "calendar_rule_id": null,
#                 "hot_live_group": null,
#                 "pre_sale_time": 0,
#                 "out_source_sku_id": null,
#                 "dd_grocery_sku_params": null,
#                 "sku_extended_attribute_dtos": null,
#                 "sku_basic_property_dtos": null,
#                 "spec_note_map": null,
#                 "delivery_schedule_dtos": null,
#                 "shipment_limit_second_list": [],
#                 "sku69_code": "",
#                 "outer_product_url": null,
#                 "internal_product_url": null,
#                 "vas_platform_install_convert_id": null,
#                 "vas_platform_dismantle_and_home_install_convert_id": null,
#                 "vas_platform_dismantle_taken_and_home_install_convert_id": null
#             },
#             {
#                 "id": null,
#                 "sku_id": 1874880557323,
#                 "sku_sn": null,
#                 "carnival_price": 0,
#                 "init_quantity": 0,
#                 "is_onsale": 1,
#                 "limit_quantity": 999999,
#                 "multi_price": 1880,
#                 "multi_price_in_yuan": null,
#                 "price": 1980,
#                 "price_in_yuan": null,
#                 "quantity": 1000,
#                 "reserve_quantity": 0,
#                 "weight": 0,
#                 "thumb_url": "https://img.pddpic.com/mms-goods-image/2026-03-24/15a504df-6dba-4276-9aeb-ae0aec4870d2.jpeg.a.jpeg",
#                 "thumb_url_file_id": 85819409353,
#                 "thumb_url_status": null,
#                 "thumb_url_is_deleted": null,
#                 "quantity_delta": 1000,
#                 "spec": [
#                     {
#                         "parent_id": 1215,
#                         "parent_name": "颜色",
#                         "spec_id": 23449387251,
#                         "spec_name": "黑色【三】双",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     },
#                     {
#                         "parent_id": 1226,
#                         "parent_name": "尺码",
#                         "spec_id": 55256868,
#                         "spec_name": "【150-175】",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     }
#                 ],
#                 "out_sku_sn": "2049-GXH3",
#                 "batch_id": null,
#                 "priority": 2,
#                 "ware_id": null,
#                 "ware_biz_type": null,
#                 "advice_price": null,
#                 "length": null,
#                 "oversea_sku": {
#                     "specifications": null,
#                     "measurement_code": null,
#                     "measurement_unit": null,
#                     "taxation": null,
#                     "record_id_list": null
#                 },
#                 "cspu_id": null,
#                 "child_skus": null,
#                 "ref_sku_commit_id": 3137984564888,
#                 "start_time": null,
#                 "end_time": null,
#                 "sku_srv_templates": null,
#                 "calendar_rule_id": null,
#                 "hot_live_group": null,
#                 "pre_sale_time": 0,
#                 "out_source_sku_id": null,
#                 "dd_grocery_sku_params": null,
#                 "sku_extended_attribute_dtos": null,
#                 "sku_basic_property_dtos": null,
#                 "spec_note_map": null,
#                 "delivery_schedule_dtos": null,
#                 "shipment_limit_second_list": [],
#                 "sku69_code": "",
#                 "outer_product_url": null,
#                 "internal_product_url": null,
#                 "vas_platform_install_convert_id": null,
#                 "vas_platform_dismantle_and_home_install_convert_id": null,
#                 "vas_platform_dismantle_taken_and_home_install_convert_id": null
#             },
#             {
#                 "id": null,
#                 "sku_id": 1874880557324,
#                 "sku_sn": null,
#                 "carnival_price": 0,
#                 "init_quantity": 0,
#                 "is_onsale": 1,
#                 "limit_quantity": 999999,
#                 "multi_price": 980,
#                 "multi_price_in_yuan": null,
#                 "price": 1080,
#                 "price_in_yuan": null,
#                 "quantity": 1000,
#                 "reserve_quantity": 0,
#                 "weight": 0,
#                 "thumb_url": "https://img.pddpic.com/mms-goods-image/2026-03-24/c23d3e7d-28c3-4025-bc56-75d18afa6c49.jpeg",
#                 "thumb_url_file_id": 85818931896,
#                 "thumb_url_status": null,
#                 "thumb_url_is_deleted": null,
#                 "quantity_delta": 1000,
#                 "spec": [
#                     {
#                         "parent_id": 1215,
#                         "parent_name": "颜色",
#                         "spec_id": 26866357729,
#                         "spec_name": "白色【一】双",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     },
#                     {
#                         "parent_id": 1226,
#                         "parent_name": "尺码",
#                         "spec_id": 55256868,
#                         "spec_name": "【150-175】",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     }
#                 ],
#                 "out_sku_sn": "2049-GXB1",
#                 "batch_id": null,
#                 "priority": 3,
#                 "ware_id": null,
#                 "ware_biz_type": null,
#                 "advice_price": null,
#                 "length": null,
#                 "oversea_sku": {
#                     "specifications": null,
#                     "measurement_code": null,
#                     "measurement_unit": null,
#                     "taxation": null,
#                     "record_id_list": null
#                 },
#                 "cspu_id": null,
#                 "child_skus": null,
#                 "ref_sku_commit_id": 3137984564889,
#                 "start_time": null,
#                 "end_time": null,
#                 "sku_srv_templates": null,
#                 "calendar_rule_id": null,
#                 "hot_live_group": null,
#                 "pre_sale_time": 0,
#                 "out_source_sku_id": null,
#                 "dd_grocery_sku_params": null,
#                 "sku_extended_attribute_dtos": null,
#                 "sku_basic_property_dtos": null,
#                 "spec_note_map": null,
#                 "delivery_schedule_dtos": null,
#                 "shipment_limit_second_list": [],
#                 "sku69_code": "",
#                 "outer_product_url": null,
#                 "internal_product_url": null,
#                 "vas_platform_install_convert_id": null,
#                 "vas_platform_dismantle_and_home_install_convert_id": null,
#                 "vas_platform_dismantle_taken_and_home_install_convert_id": null
#             },
#             {
#                 "id": null,
#                 "sku_id": 1874880557325,
#                 "sku_sn": null,
#                 "carnival_price": 0,
#                 "init_quantity": 0,
#                 "is_onsale": 1,
#                 "limit_quantity": 999999,
#                 "multi_price": 1480,
#                 "multi_price_in_yuan": null,
#                 "price": 1580,
#                 "price_in_yuan": null,
#                 "quantity": 1000,
#                 "reserve_quantity": 0,
#                 "weight": 0,
#                 "thumb_url": "https://img.pddpic.com/mms-goods-image/2026-03-24/c00bfc5d-d3f5-4c7e-ab77-e9991bf5196e.jpeg.a.jpeg",
#                 "thumb_url_file_id": 85818948002,
#                 "thumb_url_status": null,
#                 "thumb_url_is_deleted": null,
#                 "quantity_delta": 1000,
#                 "spec": [
#                     {
#                         "parent_id": 1215,
#                         "parent_name": "颜色",
#                         "spec_id": 18189593877,
#                         "spec_name": "白色【两】双",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     },
#                     {
#                         "parent_id": 1226,
#                         "parent_name": "尺码",
#                         "spec_id": 55256868,
#                         "spec_name": "【150-175】",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     }
#                 ],
#                 "out_sku_sn": "2049-GXB2",
#                 "batch_id": null,
#                 "priority": 4,
#                 "ware_id": null,
#                 "ware_biz_type": null,
#                 "advice_price": null,
#                 "length": null,
#                 "oversea_sku": {
#                     "specifications": null,
#                     "measurement_code": null,
#                     "measurement_unit": null,
#                     "taxation": null,
#                     "record_id_list": null
#                 },
#                 "cspu_id": null,
#                 "child_skus": null,
#                 "ref_sku_commit_id": 3137984564890,
#                 "start_time": null,
#                 "end_time": null,
#                 "sku_srv_templates": null,
#                 "calendar_rule_id": null,
#                 "hot_live_group": null,
#                 "pre_sale_time": 0,
#                 "out_source_sku_id": null,
#                 "dd_grocery_sku_params": null,
#                 "sku_extended_attribute_dtos": null,
#                 "sku_basic_property_dtos": null,
#                 "spec_note_map": null,
#                 "delivery_schedule_dtos": null,
#                 "shipment_limit_second_list": [],
#                 "sku69_code": "",
#                 "outer_product_url": null,
#                 "internal_product_url": null,
#                 "vas_platform_install_convert_id": null,
#                 "vas_platform_dismantle_and_home_install_convert_id": null,
#                 "vas_platform_dismantle_taken_and_home_install_convert_id": null
#             },
#             {
#                 "id": null,
#                 "sku_id": 1874880557326,
#                 "sku_sn": null,
#                 "carnival_price": 0,
#                 "init_quantity": 0,
#                 "is_onsale": 1,
#                 "limit_quantity": 999999,
#                 "multi_price": 1880,
#                 "multi_price_in_yuan": null,
#                 "price": 1980,
#                 "price_in_yuan": null,
#                 "quantity": 1000,
#                 "reserve_quantity": 0,
#                 "weight": 0,
#                 "thumb_url": "https://img.pddpic.com/mms-goods-image/2026-03-24/f49672b2-63f6-480e-8b99-6f96d9390831.jpeg.a.jpeg",
#                 "thumb_url_file_id": 85819221582,
#                 "thumb_url_status": null,
#                 "thumb_url_is_deleted": null,
#                 "quantity_delta": 1000,
#                 "spec": [
#                     {
#                         "parent_id": 1215,
#                         "parent_name": "颜色",
#                         "spec_id": 29024353275,
#                         "spec_name": "白色【三】双",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     },
#                     {
#                         "parent_id": 1226,
#                         "parent_name": "尺码",
#                         "spec_id": 55256868,
#                         "spec_name": "【150-175】",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     }
#                 ],
#                 "out_sku_sn": "2049-GXB3",
#                 "batch_id": null,
#                 "priority": 5,
#                 "ware_id": null,
#                 "ware_biz_type": null,
#                 "advice_price": null,
#                 "length": null,
#                 "oversea_sku": {
#                     "specifications": null,
#                     "measurement_code": null,
#                     "measurement_unit": null,
#                     "taxation": null,
#                     "record_id_list": null
#                 },
#                 "cspu_id": null,
#                 "child_skus": null,
#                 "ref_sku_commit_id": 3137984564891,
#                 "start_time": null,
#                 "end_time": null,
#                 "sku_srv_templates": null,
#                 "calendar_rule_id": null,
#                 "hot_live_group": null,
#                 "pre_sale_time": 0,
#                 "out_source_sku_id": null,
#                 "dd_grocery_sku_params": null,
#                 "sku_extended_attribute_dtos": null,
#                 "sku_basic_property_dtos": null,
#                 "spec_note_map": null,
#                 "delivery_schedule_dtos": null,
#                 "shipment_limit_second_list": [],
#                 "sku69_code": "",
#                 "outer_product_url": null,
#                 "internal_product_url": null,
#                 "vas_platform_install_convert_id": null,
#                 "vas_platform_dismantle_and_home_install_convert_id": null,
#                 "vas_platform_dismantle_taken_and_home_install_convert_id": null
#             },
#             {
#                 "id": null,
#                 "sku_id": 1874880557327,
#                 "sku_sn": null,
#                 "carnival_price": 0,
#                 "init_quantity": 0,
#                 "is_onsale": 1,
#                 "limit_quantity": 999999,
#                 "multi_price": 1780,
#                 "multi_price_in_yuan": null,
#                 "price": 1980,
#                 "price_in_yuan": null,
#                 "quantity": 1000,
#                 "reserve_quantity": 0,
#                 "weight": 0,
#                 "thumb_url": "https://img.pddpic.com/mms-goods-image/2026-03-24/15a504df-6dba-4276-9aeb-ae0aec4870d2.jpeg.a.jpeg",
#                 "thumb_url_file_id": 85819409353,
#                 "thumb_url_status": null,
#                 "thumb_url_is_deleted": null,
#                 "quantity_delta": 1000,
#                 "spec": [
#                     {
#                         "parent_id": 1215,
#                         "parent_name": "颜色",
#                         "spec_id": 29625045592,
#                         "spec_name": "【三】双自选",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     },
#                     {
#                         "parent_id": 1226,
#                         "parent_name": "尺码",
#                         "spec_id": 55256868,
#                         "spec_name": "【150-175】",
#                         "spec_note": null,
#                         "bundle_spec_list": null,
#                         "sku_combination": null,
#                         "is_custom": null
#                     }
#                 ],
#                 "out_sku_sn": "2049-GXH3",
#                 "batch_id": null,
#                 "priority": 6,
#                 "ware_id": null,
#                 "ware_biz_type": null,
#                 "advice_price": null,
#                 "length": null,
#                 "oversea_sku": {
#                     "specifications": null,
#                     "measurement_code": null,
#                     "measurement_unit": null,
#                     "taxation": null,
#                     "record_id_list": null
#                 },
#                 "cspu_id": null,
#                 "child_skus": null,
#                 "ref_sku_commit_id": 3137984564892,
#                 "start_time": null,
#                 "end_time": null,
#                 "sku_srv_templates": null,
#                 "calendar_rule_id": null,
#                 "hot_live_group": null,
#                 "pre_sale_time": 0,
#                 "out_source_sku_id": null,
#                 "dd_grocery_sku_params": null,
#                 "sku_extended_attribute_dtos": null,
#                 "sku_basic_property_dtos": null,
#                 "spec_note_map": null,
#                 "delivery_schedule_dtos": null,
#                 "shipment_limit_second_list": [],
#                 "sku69_code": "",
#                 "outer_product_url": null,
#                 "internal_product_url": null,
#                 "vas_platform_install_convert_id": null,
#                 "vas_platform_dismantle_and_home_install_convert_id": null,
#                 "vas_platform_dismantle_taken_and_home_install_convert_id": null
#             }
#         ],
#         "paper_net_weight": null,
#         "paper_length": null,
#         "paper_width": null,
#         "paper_plies_num": null,
#         "second_hand": 0,
#         "invoice_status": 0,
#         "invoice_mode": null,
#         "client_id": null,
#         "is_card_secret": false,
#         "is_only_for_remote_area": false,
#         "quan_guo_lian_bao": 0,
#         "zhi_huan_bu_xiu": 0,
#         "song_huo_ru_hu": null,
#         "shang_men_an_zhuang": null,
#         "song_huo_an_zhuang": null,
#         "mai_jia_zi_ti": null,
#         "show_activity_price": false,
#         "elec_goods_attributes": null,
#         "status": 2,
#         "goods_resource_descs": [],
#         "goods_resource_list": [],
#         "activity_list_image": null,
#         "first_check_time": 1774341831,
#         "min_group_price": 980,
#         "max_group_price": 1880,
#         "goods_property_list": null,
#         "must_check_type": 0,
#         "oversea_type": 0,
#         "oversea_goods": null,
#         "is_general_trade": 0,
#         "origin_country_id": 0,
#         "origin_country_name": "",
#         "size_spec_id": null,
#         "size_parent_spec_id": null,
#         "goods_name_prefix": "",
#         "customs_declaration_location": null,
#         "is_small_group": null,
#         "bad_fruit_claim": 0,
#         "bad_claim_text": "坏了包赔",
#         "lack_of_weight_claim": 0,
#         "delivery_one_day": 0,
#         "delivery_type": null,
#         "goods_pattern": 8,
#         "customizable": 0,
#         "is_group_pre_sale": 0,
#         "is_sku_pre_sale": 0,
#         "gold_price_template_id": null,
#         "gold_price_type": null,
#         "processing_charges": null,
#         "processing_charges_type": null,
#         "local_service_id_list": null,
#         "shop_group_id": null,
#         "shop_group_name": null,
#         "shoes_template_id": null,
#         "spu_id": null,
#         "spu_verison": null,
#         "goods_trade_attr": null,
#         "goods_travel_attr": null,
#         "sku_type": null,
#         "schedule_sale": {
#             "sale_type": 0,
#             "sale_time_fixed": null,
#             "sale_time": null,
#             "price_show": null
#         },
#         "send_address": "",
#         "goods_srv_templates": [],
#         "card_verification_list": null,
#         "transport_type_list": null,
#         "out_source_type": null,
#         "out_source_goods_id": null,
#         "is_all_weight_same": true,
#         "open_festival": false,
#         "two_pieces_discount": 88,
#         "promised_delivery_seconds": 0,
#         "community_group_buying": 0,
#         "purchase_info_supply": 0,
#         "ware_status": null,
#         "is_same_city_transport_goods": 0,
#         "allergy_refund": 0,
#         "goods_certificate": 0,
#         "is_customized": 0,
#         "name_prefix": "",
#         "goods_options": [
#             117,
#             54,
#             9,
#             122,
#             13
#         ],
#         "is_refundable_fifteen_day": 0,
#         "is_warranty_one_year": 0,
#         "online_explanation_video": null,
#         "privacy_delivery": 0,
#         "invoice_mode_sub_type": null,
#         "is_two_num_group": false,
#         "extend_warranty_dto": {
#             "extend_warranty": 0,
#             "extend_warranty_year": null,
#             "extend_warranty_range": null
#         },
#         "is_sku_shipment": 0,
#         "qualification_id_list": [],
#         "is_certificate_provide": 0,
#         "stock_pattern_value": null,
#         "thawed_refund": 0,
#         "damage_claim": 0,
#         "is_wp_service": 0,
#         "is_size_change_casually": 0,
#         "is_size_spec_sync_detail": 1,
#         "size_spec_url": "",
#         "is_refundable_thirty_day": 0,
#         "medical_device_confirm": 0,
#         "package_label_gallery": [],
#         "package_label_type": 0,
#         "shoes_series": null,
#         "cat_id_1": 8583,
#         "cat_id_2": 8606,
#         "cat_id_3": 26945,
#         "cat_id_4": 0
#     }
# }